---
- hosts: all
  remote_user: root
  become: yes
  tasks:
    - name: Copy the SSH private key
      copy:
        src: "{{ ssh_private_key_file }}"
        dest: /home/ubuntu/.ssh/plz.privkey
        owner: ubuntu
        group: ubuntu
        mode: 0600
    - name: Log in to AWS ECR
      shell: |
        eval "$(aws ecr get-login --no-include-email --region {{ aws_region }})"
    - name: Stop the container
      docker_container:
        name: controller
        state: absent
    - name: Start the container
      docker_container:
        name: controller
        image: "{{ image }}"
        pull: yes
        env:
          CONFIG: |
            port = 80
            data_dir = "/data"
            instances = {
              provider = "aws-ec2"
              region = "{{ aws_region }}"
              project = "{{ aws_project }}"
              worker_ami = "{{ aws_worker_ami }}"
              key_name = "{{ aws_key_name }}"
              group_name = "{{ environment_name }}"
            }
            images = {
              provider = "aws-ecr"
              region = "{{ aws_region }}"
            }
        published_ports:
          - "{{ service_port }}:80"
        volumes:
          - /cache/controller:/data
          - /home/ubuntu/.ssh/plz.privkey:/root/.ssh/id_rsa:ro
          - /var/run/docker.sock:/var/run/docker.sock
        restart_policy: unless-stopped
    - name: Set cron job for tidying
      cron:
        name: "Tidying each minute"
        job: "curl -X POST localhost:{{service_port}}/executions/tidy"
