---
- hosts: all
  remote_user: root
  become: yes
  tasks:
    - name: Copy the SSH private key
      copy:
        src: "{{ ssh_private_key_file }}"
        dest: /home/ubuntu/.ssh/batman.privkey
        owner: ubuntu
        group: ubuntu
        mode: 0600
    - name: Log in to AWS ECR
      shell: |
        eval "$(aws ecr get-login --no-include-email --region {{ aws_region }})"
    - name: Stop the container
      docker_container:
        name: controller
        state: absent
    - name: Start the container
      docker_container:
        name: controller
        image: "{{ image }}"
        pull: yes
        env:
          AWS_DEFAULT_REGION: "{{ aws_region }}"
          AWS_PROJECT: "{{ aws_project }}"
          ENVIRONMENT_NAME: "{{ environment_name }}"
          PORT: "{{ service_port }}"
        published_ports:
          - "{{ service_port }}:{{ service_port }}"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /home/ubuntu/.ssh/batman.privkey:/root/.ssh/id_rsa:ro
        restart_policy: unless-stopped
