---
- hosts: all
  remote_user: root
  become: yes
  tasks:
    - name: Copy the SSH private key
      copy:
        src: "{{ ssh_private_key_file }}"
        dest: /home/ubuntu/.ssh/plz
        owner: ubuntu
        group: ubuntu
        mode: 0600

    - name: Log in to AWS ECR
      shell: |
        eval "$(aws ecr get-login --no-include-email --region {{ aws_region }})"

    - name: Copy the Docker Compose base file
      copy:
        src: ./docker-compose.base.yml
        dest: /tmp/docker-compose.base.yml

    - name: Start the services
      docker_service:
        project_name: controller
        pull: yes
        definition:
          version: '2'

          services:
            controller:
              extends:
                file: /tmp/docker-compose.base.yml
                service: controller
              image: '{{ image }}'
              environment:
                CONFIGURATION: |
                  port = 80
                  data_dir = "/data"
                  instances = {
                    provider = aws-ec2
                    region = "{{ aws_region }}"
                    project = "{{ aws_project }}"
                    key_name = "{{ key_name }}"
                    group_name = "{{ environment_name }}"
                  }
                  images = {
                    provider = aws-ecr
                    region = "{{ aws_region }}"
                    repository = "{{ aws_project }}/plz/builds"
                  }
              ports:
                - "{{ service_port }}:80"
              volumes:
                - /cache/controller:/data
                - /home/ubuntu/.ssh/plz:/root/.ssh/id_rsa:ro

    - name: Set cron job for tidying
      cron:
        name: "Tidying each minute"
        job: "curl -X POST localhost:{{service_port}}/executions/tidy"
