---
- hosts: all
  remote_user: root
  become: yes
  tasks:
    - name: Log in to AWS ECR
      shell: |
        eval "$(aws ecr get-login --no-include-email --region {{ aws_region }})"
    - name: Stop the container
      docker_container:
        name: controller
        state: absent
    - name: Start the container
      docker_container:
        name: controller
        image: "{{ image }}"
        pull: yes
        env:
          AWS_DEFAULT_REGION: "{{ aws_region }}"
          AWS_PROJECT: "{{ aws_project }}"
          AWS_AUTOSCALING_GROUP: "{{ aws_autoscaling_group }}"
          PORT: "{{ service_port }}"
        published_ports:
          - "{{ service_port }}:{{ service_port }}"
        restart_policy: unless-stopped
