version: '2.3'

services:
  controller_localhost:
    extends:
      file: ./docker-compose.base.yml
      service: controller
    ports:
      - 5000:80
    volumes:
      - ./services/controller/config/localhost.conf:/root/server.conf:ro
      - ./cache/controller:/data
      - ./cache/results:/data/results
    depends_on:
      redis:
        condition: service_started

  controller_aws:
    extends:
      file: ./docker-compose.base.yml
      service: controller
    ports:
      - 6000:80
    volumes:
      - ./services/controller/config/_aws.conf:/root/server.conf:ro
      - ./cache/controller:/data
      - ./cache/results:/data/results
    depends_on:
      redis:
        condition: service_started
  redis:
    extends:
      file: ./docker-compose.base.yml
      service: redis
    ports:
      - 6379:6379

volumes:
  redis_data: {}
