version: "2.3"

services:
  controller:
    image: plztest/controller
    build:
      context: services/controller
      args:
        BUILD_TIMESTAMP: ${BUILD_TIMESTAMP}
    environment:
      CONFIGURATION: |
        config = { include "/root/config.json" }
        include "/root/server.conf"

        log_level = ${LOG_LEVEL:-DEBUG}
        port = 80
        redis_host = redis
        data_dir = /data
        results = {
          directory = /data/results
        }
        assumptions = {
          # We assume that 10 minutes is sufficient for socket
          # operations on the docker client
          docker_api_client_timeout_in_minutes = 10
          # We assume that the auth tokens from ECR last for
          # at least 5 minutes
          ecr_login_validity_in_minutes = 5
          # We assume that if an instance is locked for more
          # than one hour, something is wrong with it and should be
          # killed
          instance_lock_timeout = 3600
        }

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    image: redis:4
    # We assume that 5 minutes it's a reasonable
    # time as to dump the redis DB
    entrypoint: redis-server --save ${REDIS_DUMP_EVERY_SECONDS:-300} 1
    volumes:
      - /cache/redis_data:/data
