version: "2.3"

services:
  controller_localhost_no_dependencies:
    extends:
      file: ./docker-compose.base.yml
      service: controller
    ports:
      - ${PORT:-5123}:80
    volumes:
      - ./services/controller/config/localhost.conf:/root/server.conf:ro
      - ./cache/controller:/data
      - ./cache/results:/data/results

  controller_localhost:
    extends: controller_localhost_no_dependencies
    links:
      - "redis_localhost:redis"
    depends_on:
      redis_localhost:
        condition: service_started

  prebuilt_controller_localhost:
    image: prodoai/plz_controller:timestamp_${BUILD_TIMESTAMP}
    extends: controller_localhost_no_dependencies
    links:
      - "redis_localhost:redis"
    depends_on:
      redis_localhost:
        condition: service_started

  controller_aws_no_dependencies:
    extends:
      file: ./docker-compose.base.yml
      service: controller
    ports:
      - ${PORT:-5123}:80
    volumes:
      - ./services/controller/config/_aws.conf:/root/server.conf:ro
      - ./cache/controller:/data
      - ./cache/results:/data/results

  controller_aws:
    extends:
      service: controller_aws_no_dependencies
    ports:
      - ${PORT:-6000}:80
    volumes:
      - ${SECRETS_DIR}/config.json:/root/config.json:ro
      - ${SECRETS_DIR}/keys/id_rsa:/root/.ssh/id_rsa:ro
    depends_on:
      redis:
        condition: service_started

  prebuilt_local_controller_aws:
    image: prodoai/plz_controller:timestamp_${BUILD_TIMESTAMP}
    extends:
      service: controller_aws_no_dependencies
    volumes:
      - ${SECRETS_DIR}/config.json:/root/config.json:ro
      - ./services/controller/config/localserver.conf:/root/server.conf:ro
      - ${HOME}/.aws:/root/.aws
    environment:
      - CREATE_AWS_RESOURCES=yes
    links:
      - "redis_localhost:redis"
    depends_on:
      redis_localhost:
        condition: service_started
      harvester:
        condition: service_started

  redis:
    extends:
      file: ./docker-compose.base.yml
      service: redis
    ports:
      - 6379:6379

  redis_localhost:
    extends:
      service: redis
    volumes: 
      - ./cache/redis_data:/data

  harvester:
    image: plz/harvester
    environment:
      - HOST=localhost
      - PORT=${PORT:-5123}
      - WAIT_FOR_SECONDS=60
    network_mode: host

volumes:
  redis_data: {}
