version: '2.3'

services:
  controller:
    environment:
      CONFIGURATION: |
        config = { include "/root/config.json" }
        include "/root/server.conf"

        port = 80
        redis_host = redis
        data_dir = /data
        results = {
          directory = /data/results
        }
        assumptions = {
          # We assume that 10 minutes is sufficient for socket
          # operations on the docker client
          docker_api_client_timeout_in_minutes = 10
          # We assume that the auth tokens from ECR last for
          # at least 5 minutes
          ecr_login_validity_in_minutes = 5
        }

    volumes:
      - ${SECRETS_DIR}/config.json:/root/config.json:ro
      - ${SECRETS_DIR}/keys/id_rsa:/root/.ssh/id_rsa:ro
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    image: redis:4
    # We assume that 5 minutes it's a reasonable
    # time as to dump the redis DB
    entrypoint: redis-server --save 300 1
    volumes:
      - /cache/redis_data:/data
