---
- hosts: all
  vars:
    volume: /dev/xvdx
    fstype: ext4
  remote_user: root
  become: yes
  tasks:
    - name: Create the cache user group
      group:
        name: cache
    - name: Create a filesystem on the cache volume
      filesystem:
        dev: "{{ volume }}"
        fstype: "{{ fstype }}"
    - name: Mount the cache volume
      mount:
        src: "{{ volume }}"
        path: /cache
        fstype: "{{ fstype }}"
        state: mounted
    - name: Set ownership for the cache volume
      file:
        path: /cache
        owner: root
        group: cache
        mode: u+rwx,g+rws,o-rwx
    - name: Create the Docker directory
      file:
        path: /cache/docker
        state: directory
        owner: root
        group: cache
        mode: u+rwx,g+rws,o-rwx
    - name: Stop the Docker service
      service:
        name: docker
        state: stopped
    - name: Delete the Docker directory
      file:
        path: /var/lib/docker
        state: absent
    - name: Link the Docker directory to the cache volume
      file:
        src: /cache/docker
        dest: /var/lib/docker
        state: link
        owner: root
        group: root
    - name: Start the Docker service
      service:
        name: docker
        state: started
