---
# Common packages
- hosts: all
  remote_user: root
  become: yes
  tasks:
    - name: Add the Ansible APT repository
      apt_repository:
        repo: ppa:ansible/ansible
    - name: Update the APT repositories
      apt:
        update_cache: yes
    - name: Install aptitude
      apt:
        name: aptitude
    - name: Upgrade everything
      apt:
        upgrade: full
    - name: Install the fundamentals
      apt:
        name: '{{ item }}'
      with_items:
        - ansible
        - apt-transport-https
        - ca-certificates
        - curl
        - mosh
        - python-pip
    - name: Install awscli
      pip:
        name: awscli

# Build packages
- hosts: controller
  remote_user: root
  become: yes
  vars:
    packer_version: 1.1.3
    zip: /tmp/packer.zip
  tasks:
    - name: Install zsh
      apt:
        name: zsh
    - name: Install make
      apt:
        name: make
    - name: Install unzip
      apt:
        name: unzip
    - name: Check whether Packer is present
      stat: path=/etc/shorewall/rules
      register: packer
    - name: Download Packer
      get_url:
        url: "https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_amd64.zip"
        dest: "{{ zip }}"
      when: not packer.stat.exists
    - name: Install Packer
      unarchive:
        src: "{{ zip }}"
        dest: /usr/local/bin
        remote_src: yes
      when: not packer.stat.exists

- hosts: all
  remote_user: root
  become: yes
  tasks:
    - name: Create the Docker service configuration directory
      file:
        path: /etc/systemd/system/docker.service.d
        state: directory
    - name: Configure the Docker daemon to open itself over TCP
      copy:
        dest: /etc/systemd/system/docker.service.d/override.conf
        content: |
          [Service]
          ExecStart=
          ExecStart=/usr/bin/dockerd -H fd:// -H unix:///var/run/docker.sock -H tcp://0.0.0.0:2375
    - name: Grab the Docker GPG keys
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    - name: Add the Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable

- hosts: controller
  remote_user: root
  become: yes
  tasks:
    - name: Update the APT repositories
      apt:
        update_cache: yes
    - name: Install Docker
      apt:
        name: '{{ item }}'
      with_items:
        - docker-ce
        - python-docker
        - docker-compose
    - name: Add the user to the docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

- hosts: worker
  remote_user: root
  become: yes
  tasks:
    - name: Grab the NVIDIA-Docker GPG keys
      shell: |
        curl -fsSL https://nvidia.github.io/nvidia-docker/gpgkey | apt-key add -
    - name: Add the NVIDIA-Docker APT repository
      shell: curl -fsSL https://nvidia.github.io/nvidia-docker/ubuntu16.04/amd64/nvidia-docker.list > /etc/apt/sources.list.d/nvidia-docker.list
    - name: Update the APT repositories
      apt:
        update_cache: yes
    - name: Install Docker 17.12.0 # nvidia-docker doesn't yet support 17.12.1
      apt:
        name: docker-ce=17.12.0~ce-0~ubuntu
        force: yes
    - name: Install NVIDIA-Docker
      apt:
        name: nvidia-docker2
    - name: Install libcuda
      apt:
        name: libcuda1-384
    - name: Add the user to the docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
