---
# Common packages
- hosts: all
  remote_user: root
  become: yes
  tasks:
    - name: Update the APT repositories
      apt:
        update_cache: yes
    - name: Install aptitude
      apt:
        name: aptitude
    - name: Upgrade everything
      apt:
        upgrade: full
    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
    - name: Install ca-certificates
      apt:
        name: ca-certificates
    - name: Install curl
      apt:
        name: curl
    - name: Install mosh
      apt:
        name: mosh
    - name: Install python-pip
      apt:
        name: python-pip
    - name: Install awscli
      pip:
        name: awscli

# Build packages
- hosts: build
  remote_user: root
  become: yes
  vars:
    packer_version: 1.1.3
    zip: /tmp/packer.zip
  tasks:
    - name: Install zsh
      apt:
        name: zsh
    - name: Install make
      apt:
        name: make
    - name: Install unzip
      apt:
        name: unzip
    - name: Check whether Packer is present
      stat: path=/etc/shorewall/rules
      register: packer
    - name: Download Packer
      get_url:
        url: "https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_amd64.zip"
        dest: "{{ zip }}"
      when: not packer.stat.exists
    - name: Install Packer
      unarchive:
        src: "{{ zip }}"
        dest: /usr/local/bin
        remote_src: yes
      when: not packer.stat.exists

- hosts: all
  remote_user: root
  become: yes
  tasks:
    - name: Grab the Docker GPG keys
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    - name: Add the Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    - name: Install Docker
      apt:
        name: docker-ce
        update_cache: yes

- hosts: experiments
  remote_user: root
  become: yes
  tasks:
    - name: Grab the NVIDIA-Docker GPG keys
      shell: |
        curl -fsSL https://nvidia.github.io/nvidia-docker/gpgkey | apt-key add -
    - name: Add the NVIDIA-Docker APT repository
      shell: curl -fsSL https://nvidia.github.io/nvidia-docker/ubuntu16.04/amd64/nvidia-docker.list > /etc/apt/sources.list.d/nvidia-docker.list
    - name: Install NVIDIA-Docker
      apt:
        name: nvidia-docker2
        update_cache: yes
    - name: Install libcuda
      apt:
        name: libcuda1-384
    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
