name: default
channels:
  - pytorch
  - defaults
dependencies:
  - llvmlite=0.27.0
  - numba=0.42.0
  - numpy=1.15.4
  - protobuf=3.6.1
  - PyYAML=3.13
  - scikit-learn=0.20.2
  - scipy=1.2.0
  - six=1.12.0
  - pytorch=1.0.0
  - torchvision=0.2.1
  - tqdm=4.29.1
  - ujson=1.35
  - pip:
      - tensorboardx
